name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Slurm ${{ matrix.slurm }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
      options: --user root

    env:
      SOURCEDIR: ${{ github.workspace }}
      BUILDDIR: ${{ github.workspace}}/build

    strategy:
      fail-fast: false

      matrix:
        container:
          - ubuntu:noble
          - ubuntu:plucky
        include:
          - container: ubuntu:noble
            slurm: 23.11
          - container: ubuntu:plucky
            slurm: 24.11

    steps:
      - run: apt-get update -y

      - run: apt-get install -y cmake g++ ninja-build libslurm-dev bats

      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -GNinja -S $SOURCEDIR -B $BUILDDIR

      - name: Build
        run: cmake --build $BUILDDIR

      - name: Test
        run: ctest --test-dir $BUILDDIR --output-on-failure
